resolver: nightly-2021-03-25

packages:
- .

extra-deps:
- git: git@github.com:yesodweb/persistent
  commit: f7ad9b05a1ee899c6800962cbc795b39d01c5643
  subdirs:
    - persistent
    - persistent-sqlite
    - persistent-mysql
    - persistent-postgresql
- git: git@github.com:bitemyapp/esqueleto
  commit: c3b9f0390fb89ced3bb86943c24627028b11bea6
