resolver: nightly-2021-03-25

packages:
- .

extra-deps:
- persistent-2.13.0.0
- persistent-sqlite-2.13.0.0
- persistent-mysql-2.13.0.0
- persistent-postgresql-2.13.0.0
- esqueleto-3.4.2.1
- lift-type-0.1.0.1
